config/routes.rb
Rails.application.routes.draw do
  get 'access/new'
  get 'access/create'
  get 'access/destroy'
  get 'admin/index'
  resources :users
  resources :carts
  resources :lineitems
  resources :orders
  # resources :access
  get 'shopper/index'
  # get '/', to: 'shopper#index'
  root "shopper#index"  # Better to do this short form rather than above, because you need root

  get 'shopper', to: 'shopper#index'
  get 'admin', to: 'admin#index'
  get 'login', to: "access#new"

  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/lineitem.rb
class Lineitem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  belongs_to :order, optional: true

  def item_total_price
    self.product.price * self.quantity
  end
end

app/controllers/lineitems_controller.rb
class LineitemsController < ApplicationController
  # skip_before_action :authorize
  include CurrentCart

  before_action :set_cart

  before_action :set_lineitem, only: [:show, :edit, :update, :destroy]

  # GET /lineitems
  # GET /lineitems.json
  def index
    @lineitems = Lineitem.all
  end

  # GET /lineitems/1
  # GET /lineitems/1.json
  def show
  end

  # GET /lineitems/new
  def new
    @lineitem = Lineitem.new
  end

  # GET /lineitems/1/edit
  def edit
  end

  # POST /lineitems
  # POST /lineitems.json
  def create
    # @lineitem = Lineitem.new(lineitem_params)

    product = Product.find(params[:product_id])
    # @lineitem = @cart.lineitems.build(product_id: product)
    @lineitem = @cart.add_item(product.id)

    respond_to do |format|
      if @lineitem.save
        format.html { redirect_to shopper_url, notice: 'Lineitem was successfully created.' }
        format.json { render :show, status: :created, location: @lineitem }
        format.js
      else
        format.html { render :new }
        format.json { render json: @lineitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lineitems/1
  # PATCH/PUT /lineitems/1.json
  def update
    respond_to do |format|
      if @lineitem.update(lineitem_params)
        format.html { redirect_to @lineitem, notice: 'Lineitem was successfully updated.' }
        format.json { render :show, status: :ok, location: @lineitem }
      else
        format.html { render :edit }
        format.json { render json: @lineitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lineitems/1
  # DELETE /lineitems/1.json
  def destroy
    @lineitem.destroy
    respond_to do |format|
      format.html { redirect_to lineitems_url, notice: 'Lineitem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lineitem
      @lineitem = Lineitem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lineitem_params
      params.require(:lineitem).permit(:product_id, :cart_id)
    end
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/views/lineitems/_form.html.erb
<%= form_with(model: lineitem, local: true) do |form| %>
  <% if lineitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lineitem.errors.count, "error") %> prohibited this lineitem from being saved:</h2>

      <ul>
        <% lineitem.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lineitems/create.js.erb
document.getElementById("cart").innerHTML = "<%= escape_javascript render(@cart) %>";

app/views/lineitems/edit.html.erb
<h1>Editing Lineitem</h1>

<%= render 'form', lineitem: @lineitem %>

<%= link_to 'Show', @lineitem %> |
<%= link_to 'Back', lineitems_path %>

app/views/lineitems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lineitems</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lineitems.each do |lineitem| %>
      <tr>
        <td><%= lineitem.product_id %></td>
        <td><%= lineitem.cart_id %></td>
        <td><%= link_to 'Show', lineitem %></td>
        <td><%= link_to 'Edit', edit_lineitem_path(lineitem) %></td>
        <td><%= link_to 'Destroy', lineitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lineitem', new_lineitem_path %>

app/views/lineitems/new.html.erb
<h1>New Lineitem</h1>

<%= render 'form', lineitem: @lineitem %>

<%= link_to 'Back', lineitems_path %>

app/views/lineitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @lineitem.product_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @lineitem.cart_id %>
</p>

<%= link_to 'Edit', edit_lineitem_path(@lineitem) %> |
<%= link_to 'Back', lineitems_path %>